### ISSUE TITLE
爬取图片出错

### ISSUE THREAD

**Issue by YanYuanFE** [paperen/website-clone#6]
python clone.py -u http://d.u.mgd5.com/c/ttfc/x0an/index.html\?t\=1373347669\&custom\=\&crid\=\&s\=5\&from\=groupmessage\&isappinstalled\=0，

这个站点，图片和css没爬到。感谢。

**Comment by paperen** [comment]
> python clone.py -u [http://d.u.mgd5.com/c/ttfc/x0an/index.html\?t\=1373347669\&custom\=\&crid\=\&s\=5\&from\=groupmessage\&isappinstalled\=0，](http://d.u.mgd5.com/c/ttfc/x0an/index.html%5C?t%5C=1373347669%5C&custom%5C=%5C&crid%5C=%5C&s%5C=5%5C&from%5C=groupmessage%5C&isappinstalled%5C=0%EF%BC%8C)
> 
> 这个站点，图片和css没爬到。感谢。

抱歉，不支持爬取动态加载js与css的站点
